-- Mizpah Lodge #302 Camp App — Supabase Schema
-- Run this in the Supabase SQL editor on a fresh project before running seed.sql

-- ── Tables ────────────────────────────────────────────────────────────────────

create table rsvp (
  id          bigint generated by default as identity primary key,
  name        text    not null,
  fri         boolean not null default true,
  sat         boolean not null default true,
  shirt       text    not null default 'XL',
  sort_order  int     not null default 0,
  created_at  timestamptz default now()
);

create table pack_list_categories (
  id          bigint generated by default as identity primary key,
  category    text    not null,
  color       text    not null default '#3a3020',
  list_type   text    not null default 'shopping',   -- 'gear' | 'shopping'
  sort_order  int     not null default 0
);

create table pack_list_items (
  id          bigint generated by default as identity primary key,
  category_id bigint  not null references pack_list_categories(id) on delete cascade,
  uuid        uuid    not null default gen_random_uuid(),
  item        text    not null,
  qty         text    not null default '',
  note        text    not null default '',
  sort_order  int     not null default 0
);

create table menu_days (
  id          bigint generated by default as identity primary key,
  day         text    not null,
  color       text    not null default '#7a5010',
  sort_order  int     not null default 0
);

create table menu_meals (
  id          bigint generated by default as identity primary key,
  day_id      bigint  not null references menu_days(id) on delete cascade,
  meal        text    not null,
  name        text    not null,
  note        text    not null default '',
  sort_order  int     not null default 0
);

create table menu_meal_items (
  id          bigint generated by default as identity primary key,
  meal_id     bigint  not null references menu_meals(id) on delete cascade,
  item_text   text    not null,
  sort_order  int     not null default 0
);

-- Shared checklist state — one row per item, updated by any user
create table checklist_state (
  item_key    text        primary key,   -- e.g. "pack-{uuid}"
  checked     boolean     not null default false,
  checked_by  text,
  updated_at  timestamptz default now()
);

-- ── Row Level Security ────────────────────────────────────────────────────────
-- All tables are public-read/write; the admin PIN gates writes in the frontend.

alter table rsvp              enable row level security;
alter table pack_list_categories enable row level security;
alter table pack_list_items   enable row level security;
alter table menu_days         enable row level security;
alter table menu_meals        enable row level security;
alter table menu_meal_items   enable row level security;
alter table checklist_state   enable row level security;

create policy "public_all" on rsvp              for all to anon using (true) with check (true);
create policy "public_all" on pack_list_categories for all to anon using (true) with check (true);
create policy "public_all" on pack_list_items   for all to anon using (true) with check (true);
create policy "public_all" on menu_days         for all to anon using (true) with check (true);
create policy "public_all" on menu_meals        for all to anon using (true) with check (true);
create policy "public_all" on menu_meal_items   for all to anon using (true) with check (true);
create policy "public_all" on checklist_state   for all to anon using (true) with check (true);

-- ── Realtime ─────────────────────────────────────────────────────────────────
-- Enable full replica identity so DELETE events carry the old row data.

alter table checklist_state replica identity full;
alter publication supabase_realtime add table checklist_state;
